# Generated by Django 3.0.8 on 2020-10-28 17:08

import app.core.models.save_reversion_mixin
import app.core.models.upload_file_config
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(help_text='Descripción del artículo', max_length=100, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('code', models.CharField(help_text='Número de artículo', max_length=30, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Número de cliente', max_length=30, unique=True, verbose_name='Código')),
                ('photo', models.ImageField(default=None, help_text='Selecciona o arrastra una foto aquí', null=True, upload_to=app.core.models.upload_file_config.UploadFileConfig('uploads/customers/', 'photo'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg'])], verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(default='', max_length=512, verbose_name='Tipo de cliente')),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'verbose_name_plural': 'Tipos de cliente',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryAssociateCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(default='', help_text='Nombre de la empresa asociada', max_length=50, verbose_name='Nombre')),
                ('reference', models.CharField(default='', help_text='Referencia de la empresa asociada', max_length=250, verbose_name='Referencia')),
                ('code', models.PositiveIntegerField(help_text='Código del socio', unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Entrega en empresa asociada',
                'verbose_name_plural': 'Entregas en empresa asociada',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryBranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(default='', help_text='Nombre de la sucursal', max_length=50, verbose_name='Nombre')),
                ('reference', models.CharField(default='', help_text='Referencia de la sucursal', max_length=250, verbose_name='Referencia')),
                ('code', models.PositiveIntegerField(help_text='Código de la sucursal', unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Entrega en sucursal',
                'verbose_name_plural': 'Entregas en sucursal',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryDistributionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(help_text='Nombre del almacén', max_length=250, verbose_name='Almacén')),
            ],
            options={
                'verbose_name': 'Entrega en Centro de distribución',
                'verbose_name_plural': 'Entregas en centro de distribución',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('number', models.PositiveIntegerField(help_text='Número de orden', unique=True, verbose_name='Orden')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='¿Pedido urgente?')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='¿Pedido entregado?')),
                ('delivered_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de entrega')),
                ('delivery_type', models.PositiveIntegerField(choices=[(1, 'Entrega en centro de distribución'), (2, 'Entrega en sucursal'), (3, 'Entrega en empresa asociada')], verbose_name='Lugar de entrega')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Customer', verbose_name='Cliente')),
                ('delivery_associate_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DeliveryAssociateCompany', verbose_name='Entrega a empresa Asociada')),
                ('delivery_branch_office', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DeliveryBranchOffice', verbose_name='Entrega a sucursal')),
                ('delivery_distribution_center', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DeliveryDistributionCenter', verbose_name='Entrega a centro de distribución')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(default='', help_text='Nombre del proveedor', max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(default='', help_text='Dirección del proveedor', max_length=250, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('qty', models.PositiveIntegerField(help_text='Cantidad a ordenar', verbose_name='Cantidad')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Article', verbose_name='Artículo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pedido - Detalle',
                'verbose_name_plural': 'Pedidos - Detalle',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CustomerType', verbose_name='Tipo de cliente'),
        ),
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='main.Supplier', verbose_name='Proveedor'),
        ),
    ]
